version: "3"

services:
    node:
        image: node:19.0.0-alpine
        user: node
        stdin_open: true
        tty: true
        working_dir: /home/node
        entrypoint: /bin/sh -c "npm install && npm run dev"
        ports:
            - 3000:3000
        volumes:
            - .:/home/node